CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "created_at" datetime NOT NULL
);

CREATE TABLE "token_blacklist" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "token" varchar(512) NOT NULL,
  "user_id" int NOT NULL,
  "expired_at" datetime NOT NULL,
  "created_at" datetime NOT NULL
);

CREATE TABLE "diaries" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255),
  "content" text NOT NULL,
  "created_at" datetime NOT NULL,
  "user_id" int NOT NULL
);

CREATE TABLE "quotes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content" text NOT NULL,
  "author" varchar(255),
  "created_at" datetime NOT NULL
);

CREATE TABLE "bookmarks" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "quote_id" int NOT NULL,
  "created_at" datetime NOT NULL
);

CREATE TABLE "questions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "question_text" text NOT NULL
);

CREATE TABLE "user_questions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "question_id" int NOT NULL
);

CREATE UNIQUE INDEX ON "user_questions" ("user_id", "question_id");

ALTER TABLE "token_blacklist" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "diaries" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "bookmarks" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "bookmarks" ADD FOREIGN KEY ("quote_id") REFERENCES "quotes" ("id");

ALTER TABLE "user_questions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_questions" ADD FOREIGN KEY ("question_id") REFERENCES "questions" ("id");
