from tortoise import BaseDBAsyncClient

RUN_IN_TRANSACTION = True


async def upgrade(db: BaseDBAsyncClient) -> str:
    return """
        CREATE TABLE IF NOT EXISTS `users` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `username` VARCHAR(20) NOT NULL,
    `email` VARCHAR(255) NOT NULL UNIQUE,
    `password_hash` VARCHAR(255) NOT NULL,
    `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `diaries` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `title` VARCHAR(255) NOT NULL,
    `content` LONGTEXT NOT NULL,
    `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `user_id` INT NOT NULL,
    CONSTRAINT `fk_diaries_users_fdac245e` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `aerich` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `version` VARCHAR(255) NOT NULL,
    `app` VARCHAR(100) NOT NULL,
    `content` JSON NOT NULL
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `quote` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `title` VARCHAR(200) NOT NULL,
    `content` LONGTEXT NOT NULL
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `bookmarks` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `quote_id` INT NOT NULL,
    `user_id` INT NOT NULL,
    CONSTRAINT `fk_bookmark_quote_cd830281` FOREIGN KEY (`quote_id`) REFERENCES `quote` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_bookmark_users_f866d0ef` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) CHARACTER SET utf8mb4;"""


async def downgrade(db: BaseDBAsyncClient) -> str:
    return """
        """


MODELS_STATE = (
    "eJztWl1P2zAU/StVn0DaJsgooL2lpYwOaDfINsQ0RW7itlYTuyTOSsX632c7359rWBkJ5C"
    "29vte+9/gm58TpQ9skOjTsd19taLU/tB7aGJiQXcTsb1ptsFiEVm6gYGwIR4d5CAsY29QC"
    "GmXGCTBsyEw6tDULLSgimFmxYxjcSDTmiPA0NDkY3TlQpWQK6Uwk8uMnMyOsw3to+z8Xc3"
    "WCoKHH8kQ6X1vYVbpaCNsA01PhyFcbqxoxHBOHzosVnREceCNMuXUKMbQAhXx6ajk8fZ6d"
    "V6ZfkZtp6OKmGInR4QQ4Bo2UuyEGGsEcP5aNLQqc8lXeSvsHRwfH7w8PjpmLyCSwHK3d8s"
    "La3UCBwFBpr8U4oMD1EDCGuPFtE9cp9HozYGXDF41JgMhST4LoQ1aEom8IYQxbZ0s4muBe"
    "NSCe0hkHb68AtG/yVe9MvtqR9nZ5LYQ1s9viQ29EEkMc1xBHaAJklAExCNgOgk/eh3H8Op"
    "1NAOx08hHkY3EIF8C2l8TS1RmwZ2WgTAXWtCmfAlTNgrxkFdA0oidshCITZqMaj0xAqnuh"
    "7/yLigLMatBH2Fh5N0QBvsrgsn+tyJefeSWmbd8ZAiJZ6fMRSVhXCevOYWIrgkla3wfKWY"
    "v/bN2Ohn2BILHp1BIrhn7KbZvnBBxKVEyWKtAj965v9YFZc/abzCPPcW4YA22+BKz7YyNh"
    "B+gIWAja6e3veoGn51fQAALa9EZ7/H/CJllVc4/XfuP61nCvQxDGhMxNYM3/EYauN03NkO"
    "BtQiSS1zjpIVMykxaAwVRkzdfmK8U6I0MyBi2TrxkjrdmoxjqpRoqoUUoyBgENNYfUTDCF"
    "OIOXFXif04KRkLoAWUS5/RslxrY+XDuX8s1ujHEvRsOPvnsE3t7FqNsInpcreKIb6yz0R2"
    "5sPLLZ2Gfd2JQ046cJaikijkT8nY0rsn1bIOSU+o9jmAbwlFgQTfE5XAkcBywjgLUsGk6c"
    "8lUPvzxpy8wWWAbKLtoarDxWFKSuMpGve/JJv73Of2N6SpEcvDdk6OToO0W+VI69wDRiuW"
    "r3ZpFYbhTJiyCutCK5cwiF5agrGvKauKsh/Ibwn4fwUzfsFmD74s9TX9yiD6IqKSUZWkib"
    "Zekkb6RQJYHQp5FIFXuaFUmkX9CyvYP3TU8UIyF1OQr7D2eK/NYoAaLnXk8A9/c2+YrPvH"
    "IBFGMbHsp+uh4Nyx7K6kijrd8tA9kVVSkF+PF6iw9nk+ewCYHNJ+hmqZjnIRaXszN4JSDz"
    "fFoJdEPDKnVilVf3lWqjB6JU8ECUSjwQm69UJb9SPerfG/65H9TV8ar588JWSGH9B7WnyR"
    "4="
)
