from tortoise import BaseDBAsyncClient

RUN_IN_TRANSACTION = True


async def upgrade(db: BaseDBAsyncClient) -> str:
    return """
        CREATE TABLE IF NOT EXISTS `users` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `username` VARCHAR(20) NOT NULL,
    `email` VARCHAR(255) NOT NULL UNIQUE,
    `password_hash` VARCHAR(255) NOT NULL,
    `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `diaries` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `title` VARCHAR(255) NOT NULL,
    `content` LONGTEXT NOT NULL,
    `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `user_id` INT NOT NULL,
    CONSTRAINT `fk_diaries_users_fdac245e` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `question` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `question_text` LONGTEXT NOT NULL
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `aerich` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `version` VARCHAR(255) NOT NULL,
    `app` VARCHAR(100) NOT NULL,
    `content` JSON NOT NULL
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `quote` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `title` VARCHAR(200) NOT NULL,
    `content` LONGTEXT NOT NULL
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `bookmarks` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `quote_id` INT NOT NULL,
    `user_id` INT NOT NULL,
    CONSTRAINT `fk_bookmark_quote_cd830281` FOREIGN KEY (`quote_id`) REFERENCES `quote` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_bookmark_users_f866d0ef` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) CHARACTER SET utf8mb4;"""


async def downgrade(db: BaseDBAsyncClient) -> str:
    return """
        """


MODELS_STATE = (
    "eJztWm1P2zAQ/itVP4HEJugooH0LpYwOaAdkG2KaIjdxU6uJXWJnbcX632e7eU+bNawdCe"
    "Rbe76L7547+x7HearbxIAWff+VQqf+sfZUx8CG/EdMvlerg/E4lAoBA31LKrpcQ0pAnzIH"
    "6IwLB8CikIsMSHUHjRkimEuxa1lCSHSuiLAZilyMHl2oMWJCNpSO/PjJxQgbcAqp/3c80g"
    "YIWkbMT2SIuaVcY7OxlHUwO5eKYra+phPLtXGoPJ6xIcGBNsJMSE2IoQMYFI9njivcF955"
    "YfoRLTwNVRYuRmwMOACuxSLhromBTrDAj3tDZYCmmOVd4+Dw+PDkw9HhCVeRngSS4/kivD"
    "D2haFEoKvW53IcMLDQkDCGuIm0yd8p9FpD4CyHL2qTAJG7ngTRhywLRV8QwhiWzoZwtMFU"
    "syA22VCAt58B2jfltnWh3O409ndFLIQX86LEu95IQw4JXEMcoQ2QlQfEwGAzCG69DuP4NZ"
    "vrANhsrkZQjMUhHANKJ8QxtCGgwzxQpgxLWpTbAFV3oAhZAyyN6BkfYciGy1GNWyYgNTzT"
    "9/6PggLMYzB62Jp5CyIDX7Vz3b5TlesvIhKb0kdLQqSobTHSkNJZQrpzlEhF8JDa9456UR"
    "N/aw+9blsiSCgzHTljqKc+1IVPwGVEw2SiASOydn2pD8xcdL/BKLKPC0Ef6KMJ4NUfGwkr"
    "wEDAQZCm03/qGZ5f3kILSGjTifb6/xl/yKyYOZ77hetLw1yHIPQJGdnAGf0jDKfeY0qGhC"
    "gT0iCrCic9ZDfspARgYEqvxdxiplhlLKGMQcms5oyR0qxYY5lYI0PMykUZA4OqNYetmWAG"
    "8ZK+rMLpihKMmJQFyKyW275XY93Wh2vnWrnfjXXcq173k68egbd11TutCM/rJTzRxLpj45"
    "mJjVtWiX3RxKaomXiboOVqxBGLv3fjgqRvAw05xf7jGKYBPCcORCa+hDOJY4d7BLC+rA0n"
    "3vIVD79V1JaLHTAJmF20NHh4PCjIFsxEuWspZ+36fPWJaZskOTg3LOHJ0TPFaqocO8BUZL"
    "loazOLLFeM5FU0rjQjeXQJg/laV9TkLfWuquFXDf9lGn5qwW4Athv/OeXFLboRFYkp3biQ"
    "ejGnmFIwlsmUHqNaFVEq2J6WRZT8zGkMTnO9FksZVi/HwpdjOS6NtrmwFeggfbhsWXsjmY"
    "sahDrVki7Rkv4FHertxeteFURMyrKM/8NlgVgaOUD01MsJ4MH+Op/ncK2VAMqxNW9bPt/1"
    "unlvWwyks9rvmoVoQY8fGfiJeLMbS7KH7MVPzuIBBWosCzK+lC56LD2LK/oqVVcpUVd5c9"
    "fPa22IjYwNsZFjQ6yun7fHsNNfJEFD68/SSai+SnpGU5j/Ad3EBSk="
)
